import 'dart:developer';
import 'dart:io';

import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:jumper/src/Bloc/models/pop_up_model.dart';
import 'package:jumper/src/Core/constants/colors/app_colors.dart';
import 'package:jumper/src/Core/constants/decorations/app_Insets.dart';
import 'package:jumper/src/Core/constants/decorations/app_durations.dart';
import 'package:jumper/src/Core/constants/decorations/app_physics.dart';
import 'package:jumper/src/Core/constants/strings/assets.dart';
import 'package:jumper/src/Core/resources/data_state.dart';
import 'package:jumper/src/Core/services/network/request_status.dart';
import 'package:jumper/src/Core/utils/extensions.dart';
import 'package:jumper/src/Core/utils/keyboard_utils.dart';
import 'package:jumper/src/Core/utils/storage_util.dart';
import 'package:jumper/src/Core/utils/utils.dart';
import 'package:jumper/src/Features/shared/ChatDetailsFeature/bloc/controller/chat_properties_controller.dart';
import 'package:jumper/src/Features/shared/ChatDetailsFeature/bloc/controller/fetch_messages_controller.dart';
import 'package:jumper/src/Features/shared/ChatDetailsFeature/ui/screens/imports_chat_details.dart';
import 'package:jumper/src/Features/shared/ChatsFeature/bloc/model/message_model.dart';
import 'package:jumper/src/Ui/TextFields/text_field_default.dart';
import 'package:jumper/src/Ui/animation/animated_wrapper.dart';
import 'package:jumper/src/Ui/appbars/default_appbar.dart';
import 'package:jumper/src/Ui/builders/conditional_builder.dart';
import 'package:jumper/src/Ui/loading/loading_box.dart';
import 'package:jumper/src/Ui/pop_up/default_pop_up_button.dart';
import 'package:jumper/src/Ui/text/custom_text.dart';

import '../../../../../Bloc/models/FetchMessageResponse.dart';
import '../../../../../Core/services/image_network.dart';
import '../../../../../Ui/keyboard_visibility_builder.dart';
import '../../bloc/Parameters/send_message_parameters.dart';

// part 'chat_text_field_message.dart';
part 'appbar_chat_details.dart';
part 'chat_bubble.dart';
part 'chat_builder.dart';
part 'chat_details_options.dart';
// part 'chat_body.dart';
part 'chat_send_button.dart';
part 'chat_send_listtile.dart';
part 'chat_wrapper.dart';
